/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.19
 * Generated at: 2019-06-23 09:40:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.Date;

public final class aircraft_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);

    try {
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      XPassengersWeb.XPassengersUtils utils = null;
      utils = (XPassengersWeb.XPassengersUtils) _jspx_page_context.getAttribute("utils", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (utils == null){
        utils = new XPassengersWeb.XPassengersUtils();
        _jspx_page_context.setAttribute("utils", utils, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      XPassengersWeb.databaseAccess dao = null;
      dao = (XPassengersWeb.databaseAccess) _jspx_page_context.getAttribute("dao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (dao == null){
        dao = new XPassengersWeb.databaseAccess();
        _jspx_page_context.setAttribute("dao", dao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

	int id = Integer.valueOf(request.getParameter("id"));
	ResultSet aircraft = dao.getSingleContent("*", "airlines_airplanes", id);
	ResultSet aircraftDetail = dao.getSingleContent("*", "airplanes", aircraft.getInt("airplaneid"));

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("window.onload = function () {\r\n");
      out.write("\tvar sliderFirst = document.getElementById(\"xp_sliderFirst\");\r\n");
      out.write("\tvar outputFirst = document.getElementById(\"xp_sliderFirstValue\");\r\n");
      out.write("\toutputFirst.innerHTML = sliderFirst.value;\r\n");
      out.write("\tsliderFirst.oninput = function() {\r\n");
      out.write("\t\toutputFirst.innerHTML = this.value;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar sliderBusiness = document.getElementById(\"xp_sliderBusiness\");\r\n");
      out.write("\tvar outputBusiness = document.getElementById(\"xp_sliderBusinessValue\");\r\n");
      out.write("\toutputBusiness.innerHTML = sliderBusiness.value;\r\n");
      out.write("\tsliderBusiness.oninput = function() {\r\n");
      out.write("\t\toutputBusiness.innerHTML = this.value;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar sliderEconomy = document.getElementById(\"xp_sliderEconomy\");\r\n");
      out.write("\tvar outputEconomy = document.getElementById(\"xp_sliderEconomyValue\");\r\n");
      out.write("\toutputEconomy.innerHTML = sliderEconomy.value;\r\n");
      out.write("\tsliderEconomy.oninput = function() {\r\n");
      out.write("\t\toutputEconomy.innerHTML = this.value;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<form method=\"post\" action=\"/EditAircraftServlet\">\r\n");
      out.write("\t<h3>");
      out.print( aircraftDetail.getString("name") );
      out.write("</h3>\r\n");
      out.write("\t<div class=\"xp_seatconfig\">\r\n");
      out.write("\t\t<div class=\"xp_sliderWrapper\">\r\n");
      out.write("\t\t\t<label for=\"sliderFirst\" class=\"xp_sliderLabel\">First</label>\r\n");
      out.write("\t\t\t<input name=\"sliderFirst\" type=\"range\" min=\"0\" max=\"");
      out.print( aircraftDetail.getInt("seats") );
      out.write("\" value=\"");
      out.print( aircraft.getInt("first") );
      out.write("\" class=\"xp_slider\" id=\"xp_sliderFirst\"/>\r\n");
      out.write("\t\t\t<span id=\"xp_sliderFirstValue\" class=\"xp_sliderValue\"></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"xp_sliderWrapper\">\r\n");
      out.write("\t\t\t<label for=\"sliderBusiness\" class=\"xp_sliderLabel\">Business</label>\r\n");
      out.write("\t\t\t<input name=\"sliderBusiness\" type=\"range\" min=\"0\" max=\"");
      out.print( aircraftDetail.getInt("seats") );
      out.write("\" value=\"");
      out.print( aircraft.getInt("business") );
      out.write("\" class=\"xp_slider\" id=\"xp_sliderBusiness\"/>\r\n");
      out.write("\t\t\t<span id=\"xp_sliderBusinessValue\" class=\"xp_sliderValue\"></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"xp_sliderWrapper\">\r\n");
      out.write("\t\t\t<label for=\"sliderEconomy\" class=\"xp_sliderLabel\">Economy</label>\r\n");
      out.write("\t\t\t<input type=\"range\" min=\"0\" max=\"");
      out.print( aircraftDetail.getInt("seats") );
      out.write("\" value=\"");
      out.print( aircraft.getInt("economy") );
      out.write("\" class=\"xp_slider\" id=\"xp_sliderEconomy\"/>\r\n");
      out.write("\t\t\t<span id=\"xp_sliderEconomyValue\" class=\"xp_sliderValue\"></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
